import { predictArtifact, projectData, projectHarness, validateArtifact, type ProjectArtifact, type ProjectSpec } from './projectModels'

const safeJSON = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c')
const escapeHTML = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!)
export function predictorHTML(spec: ProjectSpec, artifact: ProjectArtifact, nonce = '') {
  validateArtifact(spec, artifact)
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(spec.title)} · ML Quest</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f0e7;color:#14211c;font:16px/1.55 system-ui,sans-serif;padding:24px}main{max-width:700px;margin:auto}small{color:#536058}h1{font-size:clamp(25px,6vw,38px);line-height:1.1}form{display:grid;gap:18px}label{display:grid;gap:6px}input,button{font:inherit;padding:12px;border:1px solid #bac4bb;border-radius:8px;max-width:100%;min-width:0}button{background:#0b7a57;color:white;cursor:pointer}output{display:block;background:#fff;padding:20px;margin:20px 0;border-left:4px solid #0b7a57;overflow-wrap:anywhere}details{margin:20px 0}p{overflow-wrap:anywhere}#incident{background:#15261e}#health{white-space:pre-line}a{color:#0b7a57}
</style></head><body><main><small>ML QUEST / PORTABLE MODEL / stable-v1</small><h1>${escapeHTML(spec.title)}</h1><p>A real fitted model running entirely in this page. No server, uploads, or external scripts.</p><form id="predict-form">${spec.features.map((f, i) => `<label>${escapeHTML(f.label)} (${escapeHTML(f.unit)})<input name="feature-${i}" type="number" step="any" min="${f.min}" max="${f.max}" required value="${artifact.vectors[0].x[i]}"></label>`).join('')}<button type="submit">Run prediction</button></form><output id="prediction" aria-live="polite">Ready for input.</output>${spec.slug === 'keep-churn-healthy' ? '<button id="incident" type="button">Run candidate rejection & rollback drill</button><p id="health" role="status"></p>' : ''}<details><summary>Model evidence and limitations</summary><p>150 synthetic examples, in chronological order: 90 train, 30 validation, 30 held-out test. Preprocessing is fitted on training rows only. ${spec.task === 'regression' ? 'Intervals use validation residuals; this small synthetic experiment offers no real-world coverage guarantee.' : 'Probabilities and thresholds are not calibrated or validated for real decisions. A review flag is not a fraud or churn verdict.'}</p><p id="metrics"></p><p>Use this for learning only—not housing valuations, financial decisions, or automated customer actions.</p></details><small>Generated by <a href="https://bankoti.github.io/ml-quest/">ML Quest</a>. Host this single file on any static website, including GitHub Pages.</small></main><script>
const spec=${safeJSON(spec)}, artifact=${safeJSON(artifact)}, nonce=${safeJSON(nonce)};
const infer=${predictArtifact.toString()};
const form=document.getElementById('predict-form'), output=document.getElementById('prediction');
function renderPrediction(){
 try{const x=spec.features.map((_,i)=>Number(form.elements.namedItem('feature-'+i).value));const p=infer(spec,artifact.model,x);
 output.textContent=spec.task==='regression'?'Estimate: $'+(p*1000).toFixed(0)+' · validation-calibrated interval $'+((p-artifact.interval)*1000).toFixed(0)+'–$'+((p+artifact.interval)*1000).toFixed(0):'Probability: '+(p*100).toFixed(1)+'% · threshold '+artifact.threshold.toFixed(2)+' · '+(p>=artifact.threshold?'flag for human review':'no review flag');
 }catch(error){output.textContent=error.message;}
}
form.addEventListener('submit',event=>{event.preventDefault();if(form.reportValidity())renderPrediction();});
document.getElementById('metrics').textContent=Object.entries(artifact.metrics).map(([k,v])=>k.replaceAll('_',' ')+': '+v.toFixed(4)).join(' · ');
const incident=document.getElementById('incident');if(incident)incident.addEventListener('click',()=>{
 const registry={'stable-v1':artifact.model,'candidate-v2':{...artifact.model,weights:artifact.model.weights.map(w=>-w),bias:-artifact.model.bias}};
 const accepted=artifact.metrics.rejected_candidate_validation_log_loss<=artifact.metrics.validation_log_loss*.95;
 const failedPrediction=infer(spec,registry['candidate-v2'],artifact.vectors[0].x);
 const restored=infer(spec,registry['stable-v1'],artifact.vectors[0].x);
 document.getElementById('health').textContent='Labeled candidate gate: '+(accepted?'accepted':'rejected')+'\\nCandidate probability: '+failedPrediction.toFixed(4)+'\\nRollback to stable-v1: '+restored.toFixed(4)+' (matches saved model). Input drift alone never triggered this rollback.';
});
renderPrediction();
const predictions=artifact.vectors.map(v=>infer(spec,artifact.model,v.x));
parent.postMessage({type:'mlq-predictor-ready',nonce,predictions},'*');
</script></body></html>`
}

export function projectFiles(spec: ProjectSpec, code: string, artifact: ProjectArtifact) {
  const harness = projectHarness(spec)
  const driver = harness.replace(/^rows = .*$/m, "with open('data.json', encoding='utf-8') as source: rows = json.load(source)")
  return {
    'index.html': predictorHTML(spec, artifact),
    'train.py': `${code}\n\nif __name__ == '__main__':\n    import json\n    context = {'learner': dict(globals())}\n    exec(${JSON.stringify(driver)}, context)\n    with open('model.json','w') as target: json.dump(context['artifact'],target,indent=2)\n    with open('metrics.json','w') as target: json.dump(context['artifact']['metrics'],target,indent=2)\n    print('Wrote model.json and metrics.json. Rebuild index.html after any model change using build.py.')\n`,
    'tests.py': `import train\nexec(${JSON.stringify(harness)}, {'learner': vars(train)})\nprint('All project contracts passed on the versioned fixture.')\n`,
    'data.json': JSON.stringify(projectData(spec), null, 2),
    'model.json': JSON.stringify(artifact, null, 2),
    'metrics.json': JSON.stringify(artifact.metrics, null, 2),
    'build.py': `"""Update the embedded artifact after retraining; only Python stdlib needed."""\nimport json, re\nfrom pathlib import Path\na = json.loads(Path('model.json').read_text())\npage = Path('index.html').read_text()\nstart = page.index('artifact=') + len('artifact=')\nend = page.index(', nonce=', start)\nencoded = json.dumps(a).replace('<', '\\\\u003c')\nPath('index.html').write_text(page[:start] + encoded + page[end:])\nprint('Updated the self-contained predictor.')\n`,
    'README.md': `# ${spec.title}\n\nDeployment-ready learning project from ML Quest. All data is synthetic; no real customer or financial data is included. A browser preview is NOT proof that this project has been publicly published.\n\n## Reproduce locally\n\nRequires Python 3.9+; no packages to install.\n\n\x60\x60\x60sh\npython3 train.py\npython3 tests.py\npython3 build.py\npython3 -m http.server 8000\n\x60\x60\x60\n\nOpen http://localhost:8000, or double-click index.html. Predictions run offline in JavaScript. After retraining, build.py updates the embedded model; never publish a stale index.html.\n\n## Publish on GitHub Pages\n\n1. Create a repository you own, or choose a directory in your existing Pages repository.\n2. Upload index.html to the directory you want to publish. No credentials belong in this kit.\n3. In repository Settings → Pages, enable deployment from your chosen branch and folder (or use your existing Actions workflow).\n4. Wait for the Pages deployment to succeed; open the published URL and check the input form and prediction against a vector in model.json.\n5. Keep the old index.html and model.json before replacing a release, so rollback can restore both together.\n\n## Evidence\n\nDataset version: synthetic-v1. 150 chronologically ordered examples: IDs 0–89 train, 90–119 validation, 120–149 test. The model learns ${spec.features.map(f => f.name).join(', ')}. Training-only means/scales and learned parameters are serialized in model.json.\n\n${spec.description}\n\nTests validate preprocessing, changed-label learning, constant columns, finite predictions, held-out metrics, and project-specific policy behavior. Repeated test inspection during learning is not a pristine research benchmark. Use a new external holdout before claiming generalization.\n\nThe static preview ran ${artifact.vectors.length} Python/JavaScript prediction-parity checks. This proves the exported inference code runs, not that the model is safe for production. No real-world accuracy, calibrated probabilities, financial suitability, fairness, or regulatory compliance is implied.\n`,
  }
}
// Minimal uncompressed ZIP writer, deterministic and dependency-free. UTF-8
// content; filenames are fixed ASCII names generated above, never user paths.
export function zipFiles(files: Record<string, string>) {
  const encode = new TextEncoder(), parts: Uint8Array[] = [], directory: Uint8Array[] = []; let offset = 0
  const crc = (bytes: Uint8Array) => { let result = 0xffffffff; for (const byte of bytes) { result ^= byte; for (let i = 0; i < 8; i++) result = (result >>> 1) ^ ((result & 1) ? 0xedb88320 : 0) } return (result ^ 0xffffffff) >>> 0 }
  for (const [name, text] of Object.entries(files)) {
    const filename = encode.encode(name), data = encode.encode(text), checksum = crc(data), header = new Uint8Array(30 + filename.length), h = new DataView(header.buffer)
    h.setUint32(0, 0x04034b50, true); h.setUint16(4, 20, true); h.setUint16(6, 0x800, true); h.setUint16(12, 0x5d28, true); h.setUint32(14, checksum, true); h.setUint32(18, data.length, true); h.setUint32(22, data.length, true); h.setUint16(26, filename.length, true); header.set(filename, 30)
    const central = new Uint8Array(46 + filename.length), c = new DataView(central.buffer)
    c.setUint32(0, 0x02014b50, true); c.setUint16(4, 20, true); c.setUint16(6, 20, true); c.setUint16(8, 0x800, true); c.setUint16(14, 0x5d28, true); c.setUint32(16, checksum, true); c.setUint32(20, data.length, true); c.setUint32(24, data.length, true); c.setUint16(28, filename.length, true); c.setUint32(42, offset, true); central.set(filename, 46)
    parts.push(header, data); directory.push(central); offset += header.length + data.length
  }
  const end = new Uint8Array(22), e = new DataView(end.buffer), count = directory.length
  e.setUint32(0, 0x06054b50, true); e.setUint16(8, count, true); e.setUint16(10, count, true); e.setUint32(12, directory.reduce((sum, p) => sum + p.length, 0), true); e.setUint32(16, offset, true)
  const chunks = [...parts, ...directory, end], result = new Uint8Array(chunks.reduce((sum, p) => sum + p.length, 0)); let cursor = 0
  chunks.forEach(p => { result.set(p, cursor); cursor += p.length }); return result
}
