export interface GlossaryTerm { term: string; category: string; definition: string; use: string }

export const GLOSSARY: GlossaryTerm[] = [
  { term: 'Accuracy', category: 'Evaluation', definition: 'The fraction of predictions that are correct.', use: 'Useful when classes and mistake costs are reasonably balanced.' },
  { term: 'Activation', category: 'Deep learning', definition: 'A nonlinear function applied to a neuron’s weighted input.', use: 'ReLU, sigmoid, and GELU let networks model nonlinear patterns.' },
  { term: 'Anomaly detection', category: 'Unsupervised', definition: 'Finding examples that differ strongly from learned normal behavior.', use: 'Fraud, sensor failures, security events, and quality control.' },
  { term: 'Baseline', category: 'Foundations', definition: 'A simple reference result a model must beat to justify itself.', use: 'Try majority class, mean prediction, or a small hand-written rule.' },
  { term: 'Batch', category: 'Training', definition: 'A subset of training examples processed before one parameter update.', use: 'Controls memory, gradient noise, and training throughput.' },
  { term: 'Bias', category: 'Models', definition: 'An intercept parameter, or systematic error from overly simple assumptions.', use: 'Context decides whether “bias” means a learned offset or an error pattern.' },
  { term: 'Calibration', category: 'Evaluation', definition: 'Agreement between predicted confidence and observed frequency.', use: 'Among predictions scored 0.8, roughly 80% should be correct.' },
  { term: 'Classification', category: 'Models', definition: 'Predicting one of a finite set of categories.', use: 'Spam detection, diagnosis, routing, and image recognition.' },
  { term: 'Clustering', category: 'Unsupervised', definition: 'Grouping examples by similarity without known target labels.', use: 'Segmentation, exploration, and finding repeated structures.' },
  { term: 'Confusion matrix', category: 'Evaluation', definition: 'A table of true/false positives and true/false negatives.', use: 'Reveals which kind of classification error a model makes.' },
  { term: 'Cross-validation', category: 'Evaluation', definition: 'Rotating held-out folds to estimate model stability.', use: 'Especially useful when the dataset is too small for one reliable split.' },
  { term: 'Data drift', category: 'Production', definition: 'A change in the distribution of live model inputs.', use: 'A warning that production no longer resembles training.' },
  { term: 'Decision boundary', category: 'Models', definition: 'The surface separating regions assigned to different classes.', use: 'A line in two dimensions; a higher-dimensional surface in real systems.' },
  { term: 'Decision tree', category: 'Models', definition: 'A hierarchy of feature questions that routes examples to predictions.', use: 'Strong, interpretable baseline for tabular data.' },
  { term: 'Embedding', category: 'Deep learning', definition: 'A learned vector representing an item, token, or user.', use: 'Similarity search, recommendation, language, and multimodal systems.' },
  { term: 'Ensemble', category: 'Models', definition: 'A combination of multiple models whose predictions are pooled.', use: 'Random forests, gradient boosting, voting, and stacking.' },
  { term: 'Epoch', category: 'Training', definition: 'One complete pass through the training dataset.', use: 'Training may require many epochs; validation decides when to stop.' },
  { term: 'F1 score', category: 'Evaluation', definition: 'The harmonic mean of precision and recall.', use: 'A compact balance when false positives and false negatives both matter.' },
  { term: 'Feature', category: 'Foundations', definition: 'An input value supplied to a model.', use: 'Age, pixel intensity, token identity, or an engineered ratio.' },
  { term: 'Gradient', category: 'Training', definition: 'The local rate and direction of loss change for every parameter.', use: 'Optimization subtracts a scaled gradient from model parameters.' },
  { term: 'Gradient boosting', category: 'Models', definition: 'A sequential ensemble where each weak learner corrects errors left by the current model.', use: 'Strong choice for tabular regression, classification, and ranking.' },
  { term: 'Hyperparameter', category: 'Training', definition: 'A setting chosen outside training rather than learned from examples.', use: 'Learning rate, tree depth, number of clusters, or regularization strength.' },
  { term: 'Inference', category: 'Production', definition: 'Using a trained model to make predictions.', use: 'Production inference must meet latency, cost, and reliability targets.' },
  { term: 'Label', category: 'Foundations', definition: 'The target answer paired with a supervised training example.', use: 'Labels can be human judgments, measured outcomes, or derived events.' },
  { term: 'K-nearest neighbors', category: 'Models', definition: 'A model that predicts from the labels or values of the closest stored examples.', use: 'Simple local baseline when distance between scaled features is meaningful.' },
  { term: 'Learning rate', category: 'Training', definition: 'The multiplier controlling the size of optimization steps.', use: 'Too low is slow; too high can make loss unstable or divergent.' },
  { term: 'Leakage', category: 'Evaluation', definition: 'Information reaches training that would be unavailable at prediction time.', use: 'Often produces spectacular offline scores and disappointing production results.' },
  { term: 'Linear regression', category: 'Models', definition: 'A model that predicts a continuous target as a weighted sum of input features.', use: 'Interpretable baseline for numeric prediction and trend estimation.' },
  { term: 'Logistic regression', category: 'Models', definition: 'A linear classifier that maps its score through a sigmoid to produce a probability.', use: 'Interpretable baseline for binary classification and calibrated decisions.' },
  { term: 'Loss', category: 'Training', definition: 'A differentiable number describing how wrong model predictions are.', use: 'Training minimizes loss; evaluation may report different metrics.' },
  { term: 'Model', category: 'Foundations', definition: 'A parameterized rule that maps inputs to predictions.', use: 'Models range from one fitted line to billions of neural parameters.' },
  { term: 'Neural network', category: 'Deep learning', definition: 'Layers of weighted units and nonlinear activations that learn flexible representations.', use: 'Vision, language, audio, multimodal data, and large-scale prediction.' },
  { term: 'Overfitting', category: 'Training', definition: 'Learning training-specific detail that fails to generalize.', use: 'Detected when training improves while validation stalls or worsens.' },
  { term: 'Parameter', category: 'Models', definition: 'A value learned by the model during training.', use: 'Linear coefficients, tree splits, and neural network weights.' },
  { term: 'Precision', category: 'Evaluation', definition: 'Among predicted positives, the fraction that are truly positive.', use: 'Prioritize when false alarms are expensive.' },
  { term: 'Random forest', category: 'Models', definition: 'An ensemble of trees trained on varied rows and feature subsets, then averaged or voted.', use: 'Reliable nonlinear baseline for tabular data with limited preprocessing.' },
  { term: 'Recall', category: 'Evaluation', definition: 'Among actual positives, the fraction the model finds.', use: 'Prioritize when missing a positive case is expensive.' },
  { term: 'Regression', category: 'Models', definition: 'Predicting a continuous numeric value.', use: 'Price, demand, duration, risk, and temperature.' },
  { term: 'Regularization', category: 'Training', definition: 'A constraint or penalty discouraging needless complexity.', use: 'L1, L2, dropout, early stopping, and data augmentation.' },
  { term: 'Support vector machine', category: 'Models', definition: 'A classifier that seeks a wide margin between classes, anchored by support vectors.', use: 'Effective on scaled medium-sized datasets and high-dimensional features.' },
  { term: 'Target', category: 'Foundations', definition: 'The quantity a supervised model is trained to predict.', use: 'Also called the label, response, or dependent variable.' },
  { term: 'Test set', category: 'Evaluation', definition: 'A final hidden dataset used once to estimate generalization.', use: 'Keep it separate from model and threshold selection.' },
  { term: 'Threshold', category: 'Evaluation', definition: 'A cutoff turning a score or probability into an action.', use: 'Tune it to the real costs of false positives and false negatives.' },
  { term: 'Training set', category: 'Foundations', definition: 'The examples used to fit model parameters.', use: 'Usually the largest split, but never the only split.' },
  { term: 'Underfitting', category: 'Training', definition: 'A model is too constrained to capture the real signal.', use: 'Training and validation performance are both poor.' },
  { term: 'Validation set', category: 'Evaluation', definition: 'Held-out examples used to choose models and hyperparameters.', use: 'Unlike the final test set, it may guide iteration.' },
  { term: 'Weight', category: 'Models', definition: 'A learned parameter controlling the influence of an input or connection.', use: 'Training adjusts weights to reduce loss.' },
]

export const FORMULAS = [
  { name: 'Linear prediction', formula: 'ŷ = wx + b', note: 'weight × input + bias' },
  { name: 'Logistic sigmoid', formula: 'σ(z) = 1 / (1 + e⁻ᶻ)', note: 'turn a score into a probability' },
  { name: 'Euclidean distance', formula: 'd = √Σ(xᵢ − qᵢ)²', note: 'closeness used by KNN' },
  { name: 'SVM decision', formula: 'sign(w·x + b)', note: 'choose a side of the margin' },
  { name: 'Mean squared error', formula: 'MSE = Σ(y − ŷ)² / n', note: 'average squared miss' },
  { name: 'Gradient update', formula: 'w ← w − η∇L', note: 'step opposite the loss slope' },
  { name: 'Precision', formula: 'TP / (TP + FP)', note: 'trustworthiness of positive alerts' },
  { name: 'Recall', formula: 'TP / (TP + FN)', note: 'coverage of real positives' },
  { name: 'F1 score', formula: '2PR / (P + R)', note: 'harmonic balance of precision and recall' },
  { name: 'Cosine similarity', formula: 'a·b / (‖a‖‖b‖)', note: 'directional similarity between vectors' },
  { name: 'Softmax', formula: 'eˣⁱ / Σeˣʲ', note: 'turn scores into normalized weights' },
]

export const MODEL_CHOOSER = [
  ['Predict a number', 'Linear regression', 'Gradient boosting', 'Neural network'],
  ['Predict a category', 'Logistic regression', 'Random forest / boosting', 'Neural network'],
  ['Find groups', 'K-means', 'Gaussian mixture', 'Learned embeddings'],
  ['Rank items', 'Popularity baseline', 'Matrix factorization', 'Two-tower recommender'],
  ['Detect odd cases', 'Rule / z-score', 'Isolation forest', 'Autoencoder'],
]
